### ISSUE TITLE
Example of nested dnd-zones

### ISSUE THREAD

**Issue by jlkiri** [isaacHagoel/svelte-dnd-action#91]
Hey, awesome library!

I tried to create a dnd zone inside another dnd zone and get a `config.items[idx] is undefined` error. Most likely I'm doing something wrong, but I don't know what. Is there an "official" way of doing it?

**Comment by jlkiri** [comment]
I've just realized that official REPL includes examples of nested zones. But it seems that it breaks if I do certain actions.

**Comment by isaacHagoel** [comment]
Hi, can you please be more specific about which actions break it or in what way does it break? 
I tried to play with it now and encounter an exception. I documented it in #77 (which is probably the next ticket I need to pick up anyway). Are u having the same issue?

**Comment by isaacHagoel** [comment]
I pushed an improvement. please try again and let me know if u see issues.

**Comment by jlkiri** [comment]
I think I get three different errors ( 😅 ) but don't know what causes them.
One is already described #93 and I think it's not fixed ( = I still get it in 0.2.8). Another one is 

```
TypeError: dragStartMousePosition is undefined
```

![image](https://user-images.githubusercontent.com/38713361/88447704-368c1d80-ce71-11ea-8a96-22c8bab3a459.png)

Yet another one occurs after quite a lot of operations:

![image](https://user-images.githubusercontent.com/38713361/88447650-7bfc1b00-ce70-11ea-9df3-8b0b70e8ae84.png)

Here's the text log before the error above occurs:

```
Uncaught DOMException: The object could not be cloned. srcdoc:130
Uncaught DOMException: The object could not be cloned. srcdoc:134
Uncaught (in promise) TypeError: node.parentNode is null
    detach about:srcdoc line 86 > eval:79
    detach_dev about:srcdoc line 86 > eval:557
    destroy about:srcdoc line 86 > eval:2127
    destroy_block about:srcdoc line 86 > eval:335
    fix_and_destroy_block about:srcdoc line 86 > eval:340
    update_keyed_each about:srcdoc line 86 > eval:390
    update about:srcdoc line 86 > eval:2232
    update_keyed_each about:srcdoc line 86 > eval:362
    update about:srcdoc line 86 > eval:2330
    update about:srcdoc line 86 > eval:305
    flush about:srcdoc line 86 > eval:274
srcdoc line 86 > eval:79:9
dragged left 
<div class="column-content svelte-171523i" style=""> 
Object { draggedEl: div#svelte-dnd-action-dragged-el.card.svelte-171523i
 }
srcdoc line 86 > eval:1278:17
dragged entered 
<div class="column-content svelte-171523i" style=""> 
Object { indexObj: {…}, draggedEl: div#svelte-dnd-action-dragged-el.card.svelte-171523i
 }
srcdoc line 86 > eval:1262:17
dragged entered items [{"id":45,"name":"item45"},{"id":48,"name":"item48"},{"id":46,"name":"item46"}] srcdoc line 86 > eval:1270:17
dropped srcdoc line 86 > eval:1312:17
unwatching dragged element srcdoc line 86 > eval:1248:17
disarming window scroller srcdoc line 86 > eval:1040:17
unobserving srcdoc line 86 > eval:999:17
dropped in dz 
<div class="column-content svelte-171523i" style="">
srcdoc line 86 > eval:1321:21
Uncaught DOMException: The object could not be cloned. srcdoc:130
Uncaught TypeError: shadowElDropZone.children[shadowElIdx] is undefined
    animateDraggedToFinalPosition about:srcdoc line 86 > eval:1356
    handleDrop about:srcdoc line 86 > eval:1334
srcdoc line 86 > eval:1356:30
```

I guess they deserve an independent issue.

**Comment by isaacHagoel** [comment]
mmm... very strange. The only one I have never seen is the one I documented and it is fairly hard to reproduce on my machine.
When do they happen to you? Can you reproduce reliably, if so how?
Which browser are you using? What kind of input device (ex: mac trackpad)?

**Comment by jlkiri** [comment]
Browser is latest Firefox. Windows / mouse. 
Right now I get them just by randoming dragging and dropping. I'll try to reproduce it reliably and open an issue.

**Comment by isaacHagoel** [comment]
Hi Kirill,
Can u do me a favour? can you try out [this REPL](https://svelte.dev/repl/210f86392b98422899ddff227b14777b?version=3.22.2)? It has no flip animation. Pls let me know if it has the same issues.
Thanks,
Isaac

**Comment by jlkiri** [comment]
Looks like weird exceptions are gone in the non-flip version!

**Comment by isaacHagoel** [comment]
Thanks for confirming.
Yeah, I am starting to think that I will have no choice but to implement flip by myself instead of relying on Svelte for that 😞 . Going down that route might also mean ditching the `consider` events and taking care of all of the moving around the elements until a drop takes place. 
I wonder why it happens to you so frequently. Is it a relatively old/slow machine?

**Comment by jlkiri** [comment]
Yeah, Svelte's FLIP implementation is very unique. There was a PR recently that refactors a lot of animation logic, but I think it got closed. If I find time I think I can help.

My machine is not slow, I was specifically stress testing the lib by doing a lot of operations very quickly, since I want to use in my product and prepare for possible exceptions.

**Comment by jlkiri** [comment]
I must add that I was getting those exceptions only when Firefox Dev Tools was open (maybe logging slowed everything down)

**Comment by isaacHagoel** [comment]
Thanks for the info. If you'd like to help that would be great. 
Handling all of the animations within the library rather than relying o flip is something that has been a long time coming and it is going to be a massive change/ addition. That's why I have been trying to avoid it (also, I would like to keep the library as small as possible).
I wonder whether it is possible to do without also taking over all of the placeholder positioning logic away from Svelte (and even if possible maybe it will be the most robust to minimize the dependency on svelte altogether).
Do you have  a link to that PR? I am curios.

**Comment by jlkiri** [comment]
https://github.com/sveltejs/svelte/pull/4742

Also see an interesting discussion that happened around that time: https://twitter.com/AdamRackis/status/1254904079379238913

**Comment by isaacHagoel** [comment]
wow. thanks for that. 
looking at the PR and the one mentioning it I am thinking to myself: jeez, implementing some animations myself might be annoying and time consuming but it's nothing in comparison to  the massive undertaking pushkine took with that PR.
Doesn't look like his fix won't be merged anytime soon :/
You know, I was so excited about Svelte initially and thought I would champion it in my company, but unfortunately it is not quite there yet in several areas (which might be more or less critical depending on one's usecase).  This library was/is my modest attempt to help it get there.

**Comment by isaacHagoel** [comment]
If the key thing to avoid is invoking state changes while the flip animation is playing, one possible workaround/solution could be listening on `animationstart`, `animationcancel` and `animationend` events to find quiet times in which it is safe to dispatch the `consider` and `finalize` events (which trigger state changes).
This could be achieved by scheduling the `consider` and `finalize` events using a FIFO queue instead of dispatching them right away.
This shouldn't be too painful to implement. I will give it a shot when I have some time.

**Comment by isaacHagoel** [comment]
@jlkiri can you please give it another shot with version 0.2.10?

**Comment by jlkiri** [comment]
Looks good to me!

**Comment by isaacHagoel** [comment]
great!!
